### ISSUE TITLE
updating

### ISSUE THREAD

**Issue by oberstlynild** [echang15/MMM-Dad-Jokes#1]
its not updating the jokes - just loads one joke and never switches

**Comment by echang15** [comment]
What do you the refresh interval set to?

**Comment by oberstlynild** [comment]
set to 10000. I tried with "updateInterval: 10000," and also "updateInterval: '10000,'"

also i tried to change the update interval inside the MMM-Dad-Jokes.js file (i did this after trying with the config file a few time) - still not working :(

**Comment by echang15** [comment]
In that case I'm not entirely sure it's the module that's causing it - if
you've looked at the source code it's not complex at all. Do your other
modules refresh correctly?

**Comment by oberstlynild** [comment]
![2018-08-23-133412_1920x1080_scrot](https://user-images.githubusercontent.com/42640813/44523222-753f5900-a6d9-11e8-9443-67bad06eef7d.png)


![2018-08-23-133528_1920x1080_scrot](https://user-images.githubusercontent.com/42640813/44523214-6fe20e80-a6d9-11e8-8dd4-5ce1aca43a97.png)

**Comment by oberstlynild** [comment]
Yes all of my other modules refreshes correctly

**Comment by echang15** [comment]
Ok. I'll take a look at it when I get a chance, but not entirely sure what
it is. I'd be interested to see what the magic mirror logs are saying

**Comment by oberstlynild** [comment]
i got 6 hours school today to figure out how to debug hehe, will send to you when i got it

**Comment by Akdr** [comment]
Any luck? Got the same issue

**Comment by echang15** [comment]
ok - do a fresh git pull and restart magic mirror.. should be fixed now. there was an issue with the refresh function when I refactored... ie.. i fat fingered something.

**Comment by Akdr** [comment]
Thanks <3
